'use client'

import React from 'react'

export default function PrivacyPolicyPage() {
  return (
    <div className="w-full max-w-7xl mx-auto py-10 px-4 sm:px-6">
      <div className="bg-white border-2 border-ezen-outline-variant rounded-3xl p-8 sm:p-12 shadow-[6px_6px_0_0_rgba(87,52,79,0.1)] text-ezen-on-surface">
        <h1 className="font-heading text-3xl sm:text-4xl font-extrabold text-ezen-primary mb-2">
          Privacy Policy
        </h1>
        <p className="text-xs text-ezen-outline mb-8 uppercase tracking-wider font-semibold">
          Last Updated: March 2026
        </p>

        <div className="space-y-8 text-sm leading-relaxed text-ezen-on-surface-variant font-sans">
          
          <p>
            Your privacy is important to us. This policy explains how Ezen AI collects, uses, and protects your data.
          </p>

          {/* Section 1 */}
          <section className="space-y-3">
            <h2 className="text-xl font-bold text-ezen-primary font-heading">
              1. Information We Collect
            </h2>
            <p>
              We collect the following categories of information when you use the Ezen AI platform:
            </p>
            
            <h3 className="font-bold text-ezen-primary mt-2">Personal Information</h3>
            <ul className="list-disc pl-5 space-y-1">
              <li>Name, email address, phone number, and company details provided during account registration.</li>
              <li>Billing information, including GST number and payment method details.</li>
              <li>Government-issued identification when required for compliance verification.</li>
            </ul>

            <h3 className="font-bold text-ezen-primary mt-2">Usage Data</h3>
            <ul className="list-disc pl-5 space-y-1">
              <li>Log data such as IP address, browser type, device information, and access timestamps.</li>
              <li>Feature usage patterns, API call logs, and dashboard interactions.</li>
              <li>Performance metrics and error reports.</li>
            </ul>

            <h3 className="font-bold text-ezen-primary mt-2">Communication Data</h3>
            <ul className="list-disc pl-5 space-y-1">
              <li>Email content, templates, and metadata processed through our platform on your behalf.</li>
              <li>Classification results, auto-replies, and assistant logs generated by our Service.</li>
              <li>Linked inbox credentials or OAuth tokens used for email inbox integration.</li>
            </ul>

            <p className="mt-2 text-xs">
              We collect this information directly from you, automatically through your use of the Service, and from third-party integrations you connect to your Ezen AI account.
            </p>
          </section>

          {/* Section 2 */}
          <section className="space-y-3">
            <h2 className="text-xl font-bold text-ezen-primary font-heading">
              2. How We Use Your Data
            </h2>
            <p>
              We use the information we collect for the following purposes:
            </p>
            
            <h3 className="font-bold text-ezen-primary mt-2">Service Delivery</h3>
            <ul className="list-disc pl-5 space-y-1">
              <li>Providing, maintaining, and improving the Ezen AI platform and its email processing features.</li>
              <li>Analyzing, generating, and queueing replies for your integrated email accounts.</li>
              <li>Managing your account, billing, and subscription.</li>
              <li>Providing customer support and responding to your inquiries.</li>
            </ul>

            <h3 className="font-bold text-ezen-primary mt-2">Analytics & Improvement</h3>
            <ul className="list-disc pl-5 space-y-1">
              <li>Analyzing usage patterns to improve platform performance and reliability.</li>
              <li>Generating aggregated, anonymized insights to enhance our services.</li>
              <li>Conducting research and development for new features and AI capabilities.</li>
              <li>Monitoring and preventing fraud, abuse, and technical issues.</li>
            </ul>

            <h3 className="font-bold text-ezen-primary mt-2">Marketing & Communication</h3>
            <ul className="list-disc pl-5 space-y-1">
              <li>Sending service-related notifications (billing alerts, maintenance updates, security notices).</li>
              <li>Providing product updates, feature announcements, and educational content.</li>
              <li>Sharing relevant offers and promotions (only with your consent, and you may opt out at any time).</li>
            </ul>
          </section>

          {/* Section 3 */}
          <section className="space-y-3">
            <h2 className="text-xl font-bold text-ezen-primary font-heading">
              3. Data Sharing
            </h2>
            <p>
              We share your data only as necessary to deliver the Service and as described below. We never sell your personal data to third parties.
            </p>
            
            <h3 className="font-bold text-ezen-primary mt-2">Service Partners</h3>
            <ul className="list-disc pl-5 space-y-1">
              <li><strong>AI Providers</strong> — Email content chunks may be processed by LLM service partners (such as OpenAI or Google Cloud API) to extract insights and generate replies. We do not allow partners to use your data for training their model.</li>
              <li><strong>Email Providers</strong> — Credentials or authentication tokens are used to interface with Google Workspace or Microsoft 365, transmitting emails only to achieve your desired inbox settings.</li>
            </ul>

            <h3 className="font-bold text-ezen-primary mt-2">Infrastructure & Payment Processors</h3>
            <ul className="list-disc pl-5 space-y-1">
              <li>Cloud hosting providers (such as AWS or Google Cloud) for secure data storage and processing.</li>
              <li>Payment gateways (such as PhonePe) for processing subscription and credit purchases.</li>
              <li>Email delivery infrastructure partners.</li>
            </ul>

            <h3 className="font-bold text-ezen-primary mt-2">Legal & Compliance</h3>
            <ul className="list-disc pl-5 space-y-1">
              <li>When required by law, regulation, legal process, or government request.</li>
              <li>To protect the rights, property, or safety of Ezen AI, our users, or the public.</li>
              <li>In connection with a merger, acquisition, or sale of assets (with prior notice to affected users).</li>
            </ul>

            <p className="text-xs">
              All third-party partners are bound by data processing agreements and are prohibited from using your data for any purpose other than providing the specified services.
            </p>
          </section>

          {/* Section 4 */}
          <section className="space-y-3">
            <h2 className="text-xl font-bold text-ezen-primary font-heading">
              4. Data Security
            </h2>
            <p>
              We implement comprehensive security measures to protect your data:
            </p>
            
            <h3 className="font-bold text-ezen-primary mt-2">Encryption</h3>
            <ul className="list-disc pl-5 space-y-1">
              <li>All data in transit is encrypted using TLS 1.2 or higher.</li>
              <li>Data at rest is encrypted using AES-256 encryption.</li>
              <li>API keys and sensitive credentials are stored using industry-standard vault solutions.</li>
            </ul>

            <h3 className="font-bold text-ezen-primary mt-2">Certifications & Standards</h3>
            <ul className="list-disc pl-5 space-y-1">
              <li>SOC 2 & ISO 27001 compliance standards are followed to ensure security, availability, and confidentiality.</li>
              <li>Regular code audits and vulnerability assessments are performed by our engineering team.</li>
            </ul>

            <h3 className="font-bold text-ezen-primary mt-2">Access Controls</h3>
            <ul className="list-disc pl-5 space-y-1">
              <li>Role-based access controls for all internal systems.</li>
              <li>Multi-factor authentication for employee access to production systems.</li>
              <li>Regular access reviews and principle of least privilege enforcement.</li>
              <li>Comprehensive audit logging of all data access.</li>
            </ul>

            <h3 className="font-bold text-ezen-primary mt-2">Incident Response</h3>
            <ul className="list-disc pl-5 space-y-1">
              <li>Dedicated security response team with 24/7 monitoring.</li>
              <li>Documented incident response procedures.</li>
              <li>Commitment to notify affected users within 72 hours of any confirmed data breach.</li>
            </ul>
          </section>

          {/* Section 5 */}
          <section className="space-y-3">
            <h2 className="text-xl font-bold text-ezen-primary font-heading">
              5. Your Rights
            </h2>
            <p>
              You have the following rights regarding your personal data:
            </p>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>Right of Access</strong> — Request a copy of the personal data we hold about you.</li>
              <li><strong>Right to Correction</strong> — Request correction of inaccurate or incomplete personal data.</li>
              <li><strong>Right to Deletion</strong> — Request deletion of your personal data, subject to legal retention requirements.</li>
              <li><strong>Right to Data Portability</strong> — Request your data in a structured, machine-readable format.</li>
              <li><strong>Right to Object</strong> — Object to processing of your data for direct marketing purposes.</li>
              <li><strong>Right to Restrict Processing</strong> — Request restriction of processing in certain circumstances.</li>
              <li><strong>Right to Withdraw Consent</strong> — Withdraw previously given consent at any time.</li>
            </ul>
            <p className="text-xs">
              To exercise any of these rights, please contact us at <a href="mailto:privacy@ezen.ai" className="text-ezen-primary underline">privacy@ezen.ai</a>. We will respond to your request within 30 days. We may ask for additional information to verify your identity before processing your request.
            </p>
          </section>

          {/* Section 6 */}
          <section className="space-y-3">
            <h2 className="text-xl font-bold text-ezen-primary font-heading">
              6. Cookies and Tracking
            </h2>
            <p>
              We use cookies and similar tracking technologies on our website and platform:
            </p>
            <ul className="list-disc pl-5 space-y-1">
              <li><strong>Essential Cookies</strong> — Session management, authentication, security, and performance optimization.</li>
              <li><strong>Analytics Cookies</strong> — Understanding how users interact with our platform. We use tools such as Google Analytics for this purpose.</li>
              <li><strong>Marketing Cookies</strong> — Tracking effectiveness of advertising and providing relevant ads on third-party platforms.</li>
            </ul>
            <p>
              You can manage your cookie preferences through your browser settings. Please note that disabling essential cookies may affect the functionality of the Service.
            </p>
          </section>

          {/* Section 7 */}
          <section className="space-y-3">
            <h2 className="text-xl font-bold text-ezen-primary font-heading">
              7. Third-Party Services
            </h2>
            <p>
              Our platform integrates with various third-party services. When you connect these services to your Ezen AI account, your data may be shared with and processed by these providers according to their own privacy policies:
            </p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Google (Workspace APIs, OAuth, Gmail integration) — Google Privacy Policy</li>
              <li>Microsoft (Outlook APIs, OAuth integration) — Microsoft Privacy Statement</li>
              <li>Payment processors (PhonePe, etc.) — Respective payment provider privacy policies</li>
              <li>Cloud infrastructure providers — Respective cloud provider privacy policies</li>
            </ul>
            <p>
              We encourage you to review the privacy policies of any third-party services you connect. We are not responsible for the privacy practices of third-party services.
            </p>
          </section>

          {/* Section 8 */}
          <section className="space-y-3">
            <h2 className="text-xl font-bold text-ezen-primary font-heading">
              8. Children's Privacy
            </h2>
            <p>
              The Ezen AI platform is not intended for use by individuals under the age of 18. We do not knowingly collect personal data from children.
            </p>
            <p>
              If we become aware that we have collected personal data from a child under 18, we will take steps to delete that information promptly. If you believe that a child has provided us with personal data, please contact us at <a href="mailto:privacy@ezen.ai" className="text-ezen-primary underline">privacy@ezen.ai</a>.
            </p>
          </section>

          {/* Section 9 */}
          <section className="space-y-3">
            <h2 className="text-xl font-bold text-ezen-primary font-heading">
              9. GDPR Compliance
            </h2>
            <p>
              For users in the European Economic Area (EEA), we comply with the General Data Protection Regulation (GDPR). Key provisions include:
            </p>
            <ul className="list-disc pl-5 space-y-1">
              <li><strong>Legal Basis for Processing</strong> — Contract performance, legitimate interests (analytics, security), consent, and compliance with applicable laws.</li>
              <li><strong>International Data Transfers</strong> — We ensure adequate protection through Standard Contractual Clauses (SCCs) or other approved transfer mechanisms.</li>
              <li><strong>Data Protection Officer</strong> — You may contact our DPO at <a href="mailto:privacy@ezen.ai" className="text-ezen-primary underline">privacy@ezen.ai</a>.</li>
            </ul>
          </section>

          {/* Section 10 */}
          <section className="space-y-3">
            <h2 className="text-xl font-bold text-ezen-primary font-heading">
              10. Data Retention
            </h2>
            <p>
              We retain your personal data only for as long as necessary to fulfill the purposes described in this Privacy Policy:
            </p>
            <ul className="list-disc pl-5 space-y-1">
              <li><strong>Account data</strong> — Retained for the duration of your account plus 30 days after deletion.</li>
              <li><strong>Communication logs</strong> — Email processing metadata is retained for 90 days for delivery verification, then anonymized.</li>
              <li><strong>Billing data</strong> — Retained for 7 years as required by Indian tax regulations.</li>
            </ul>
            <p>
              You may request earlier deletion of your data by contacting <a href="mailto:privacy@ezen.ai" className="text-ezen-primary underline">privacy@ezen.ai</a>, subject to applicable legal retention requirements.
            </p>
          </section>

          {/* Section 11 */}
          <section className="space-y-3">
            <h2 className="text-xl font-bold text-ezen-primary font-heading">
              11. Changes to This Policy
            </h2>
            <p>
              We may update this Privacy Policy from time to time. When we make material changes, we will update the "Last Updated" date at the top of this page and notify you via email or in-app notification.
            </p>
          </section>

          {/* Section 12 */}
          <section className="space-y-3">
            <h2 className="text-xl font-bold text-ezen-primary font-heading">
              12. Contact Us
            </h2>
            <p>
              For any privacy or data protection-related questions, please contact us:
            </p>
            <ul className="space-y-1">
              <li>• <strong>Privacy Inquiries:</strong> <a href="mailto:privacy@ezen.ai" className="text-ezen-primary underline">privacy@ezen.ai</a></li>
              <li>• <strong>General Support:</strong> <a href="mailto:support@ezen.ai" className="text-ezen-primary underline">support@ezen.ai</a></li>
              <li>• <strong>Website:</strong> <a href="https://ezen.ai" className="text-ezen-primary underline">https://ezen.ai</a></li>
              <li>• <strong>Address:</strong> Ezen AI, Salem, Tamil Nadu, India</li>
            </ul>
          </section>

        </div>
      </div>
    </div>
  )
}
